version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: orenyomtov-openordex_web_1
      APP_PORT: 8020

  web:
    image: muthudotbtc/openordex:latest
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    init: true
    ports:
      - 8020:8080
